spring:
  datasource:
    url: jdbc:postgresql://dpg-d0hodrali9vc73ea6370-a.oregon-postgres.render.com:5432/tatkal?sslmode=require
    username: tatkal_user
    password: s9DGDo9zyWl3bcDevSOYGc6n8tBGIBUg
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: admin
      password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.tatkal: DEBUG  # Your base package (optional, for app-specific logs)

stripe:
  secret:
    key: sk_test_51RSc7IP6TRZTEjxOJ1zi7L6l6BcbkQ90SoQeaFbKeG8l487ymTyo0TBZDbGbNX0P9fjRq1E3A0pN06dB8ZGehfaD00yNYwyU3H
  success-url: http://localhost:3000/success
  cancel-url: http://localhost:3000/cancel
